// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TodoInput from "./TodoInput.mjs";
import LogoSvg from "./logo.svg";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as TodoListItem from "./TodoListItem.mjs";

import './App.css';
;

var logo = LogoSvg;

function App(Props) {
  var match = React.useState(function () {
        return [];
      });
  return React.createElement("div", {
              className: "App"
            }, React.createElement(TodoInput.make, {
                  setList: match[1]
                }), Belt_Array.mapWithIndex(match[0], (function (key, listItem) {
                    return React.createElement(TodoListItem.make, {
                                listItem: listItem,
                                key: String(key)
                              });
                  })));
}

var make = App;

export {
  logo ,
  make ,
  
}
/*  Not a pure module */
