// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TodoListItem(Props) {
  var listItem = Props.listItem;
  return React.createElement("li", undefined, listItem);
}

var make = TodoListItem;

export {
  make ,
  
}
/* react Not a pure module */
