// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function TodoInput(Props) {
  var setList = Props.setList;
  var match = React.useState(function () {
        return "";
      });
  var setValue = match[1];
  var value = match[0];
  var onChangeValue = function (e) {
    var target = e.currentTarget;
    return Curry._1(setValue, target.value);
  };
  return React.createElement("form", {
              onSubmit: (function (e) {
                  e.preventDefault();
                  if (value.trim() !== "") {
                    return Curry._1(setList, (function (prev) {
                                  return Belt_Array.concat(prev, [value]);
                                }));
                  }
                  
                })
            }, React.createElement("input", {
                  type: "text",
                  value: value,
                  onChange: onChangeValue
                }), React.createElement("button", {
                  type: "submit"
                }, "제출"));
}

var make = TodoInput;

export {
  make ,
  
}
/* react Not a pure module */
